email: ml-flyvemdm@teclib.com
baseurl: "/flyve-mdm-android-inventory" 
url: "https://flyve-mdm.github.io"  

# Build settings
markdown: kramdown

plugins:
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap

repository: flyve-mdm/flyve-mdm-android-inventory

sass:
    style: compressed

prose:

  rooturl: '_posts' 
  
  ignore:
    - .keep

  media: "images"

  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
